### ISSUE TITLE
Possible to remove matrix multiplication in SANet?

### ISSUE THREAD

**Issue by ebroglio** [ColorfulSoft/StyleTransfer-Colorization-SuperResolution#12]
Is it possible somehow to get rid of the two matrix multiplications in [SANet.cs](https://github.com/ColorfulSoft/StyleTransfer-Colorization-SuperResolution/blob/fa53e8ea6a5e2fbc58122d11e94019cd58003a92/Style%20Transfer/2018.%20Arbitrary%20Style%20Transfer%20with%20Style-Attentional%20Networks/Implementation/src/Network/SANet.cs#L98)? 

This is one reason it is really slow.

**Comment by GlebSBrykin** [comment]
Hello, ebroglio!
Matrix multiplication is part of any attention module, whether it is self-attention or style-attention. Regarding the speed of work, the problem is most likely directly in the implementation of matrix multiplication. I will check this code and make edits if necessary.
Sincerely,
Gleb Brykin.
