### ISSUE TITLE
Newbie in C#

### ISSUE THREAD

**Issue by leefeel** [ColorfulSoft/StyleTransfer-Colorization-SuperResolution#3]
Thank you so much for transcoding this project to c# for Windows. I wanted to use this project for some time on Windows, but I couldnt.

I don't have any experience in C#. Could you help me in the requirements and installation of this project on Windows 10? Any reference would be appreciated.

**Comment by GlebSBrykin** [comment]
Thanks for Your feedback! To use the software placed here, it is desirable to have a powerful processor in the first place. To run, download the repository and unzip it. Select the implementation of the work you would like to run and move the corresponding folder to the root of the disk or to the desktop. This is necessary in order to shorten the full path to the executable file and avoid compiler errors. For example, if You want to run Waifu2x, move the StyleTransfer-Colorization-SuperResolution\Enhancing\Waifu2x folder to C:\.  After that, go to the folder Waifu2x, find the folder Implemenyation and navigate to it. Run the Compile.bat file and wait a few seconds. You should see a Release folder that contains a single file-a neural network executable file. Run it and follow the instructions in the standard Windows graphical window(all implementations have a graphical interface). If You are using Windows 10, no additional actions will be necessary. Some implementations, such as the Gatis algorithm, can be very slow. I do not recommend using virtual machines, such as VirtualBox or others, as they will run programs at times slower.

**Comment by leefeel** [comment]
Thank you so much for your fast response. I was able to make work the Python version on my Windows. I haven't tried the C# version. 

Did you have in C# any advantage in performance?

**Comment by GlebSBrykin** [comment]
C# implementations are currently inferior to Python in performance. However, at the moment, work is underway to optimize the code using SIMD-instructions. The main goal of the project is to give the user the opportunity to try neural networks "out of the box" on an ordinary computer.
